# Naïve Bayes desde cero
Este notebook implementa un clasificador de sentimientos usando Naïve Bayes sin bibliotecas especializadas como sklearn. Ideal para proyectos académicos con restricciones de implementación desde cero.


In [131]:
# Paso 1: Cargar el dataset limpio y vectorizado
import pandas as pd

# Reemplaza con el path correcto si es necesario
#df = pd.read_csv('04tweets_vectorizados_bow.csv')
df = pd.read_csv('04tweets_vectorizados_bow.csv')
df.head()
print("Hola mundo desde la celda 1")


Hola mundo desde la celda 1


In [133]:
df.head(10)

able  absolutely  access  account  ache  actual  actually  add  addict  \
0     0           0       0        0     0       0         0    0       0   
1     0           0       0        0     0       0         0    0       0   
2     0           0       0        0     0       0         0    0       0   
3     0           0       0        0     0       0         0    0       0   
4     0           0       0        0     0       0         0    0       0   
5     0           0       0        0     0       0         0    0       0   
6     0           0       0        0     0       0         0    0       0   
7     0           0       0        0     0       0         0    0       0   
8     0           0       0        0     0       0         0    0       0   
9     0           0       0        0     0       0         0    0       0   

   afraid  ...  yer  yes  yesterday  youll  young  youre  youtube  youve  yum  \
0       0  ...    0    0          0      0      0      0        0      0    0   
1       0  ...    0    0          0      0      0      0        0      0    0   
2       0  ...    0    0          0      0      0      0        0      0    0   
3       0  ...    0    0          0      0      0      0        0      0    0   
4       0  ...    0    0          0      0      0      0        0      0    0   
5       0  ...    0    0          0      0      0      0        0      0    0   
6       0  ...    0    0          0      0      0      0        0      0    0   
7       0  ...    0    0          0      0      0      0        0      0    0   
8       0  ...    0    0          0      0      0      0        0      0    0   
9       0  ...    0    0          0      0      0      0        0      0    0   

   yummy  
0      0  
1      0  
2      0  
3      0  
4      0  
5      0  
6      0  
7      0  
8      0  
9      0  

[10 rows x 915 columns]

In [135]:
# Paso 2: Separar datos en X (features) e y (etiquetas)
# Paso 2: Separar datos en X (features) e y (etiquetas)
# 🔧 Filtrar filas donde la etiqueta es NaN
df = df[df["tweet"].notna()]

X = df.drop('tweet', axis=1)
y = df['tweet'].astype(str)  # 🔧 convertimos a str para evitar mezcla de tipos
df.head(10)


able  absolutely  access  account  ache  actual  actually  add  addict  \
0      0           0       0        0     0       0         0    0       0   
1      0           0       0        0     0       0         0    0       0   
2      0           0       0        0     0       0         0    0       0   
3      0           0       0        0     0       0         0    0       0   
4      0           0       0        0     0       0         0    0       0   
5      0           0       0        0     0       0         0    0       0   
6      0           0       0        0     0       0         0    0       0   
7      0           0       0        0     0       0         0    0       0   
9      0           0       0        0     0       0         0    0       0   
10     0           0       0        0     0       0         0    0       0   

    afraid  ...  yer  yes  yesterday  youll  young  youre  youtube  youve  \
0        0  ...    0    0          0      0      0      0        0      0   
1        0  ...    0    0          0      0      0      0        0      0   
2        0  ...    0    0          0      0      0      0        0      0   
3        0  ...    0    0          0      0      0      0        0      0   
4        0  ...    0    0          0      0      0      0        0      0   
5        0  ...    0    0          0      0      0      0        0      0   
6        0  ...    0    0          0      0      0      0        0      0   
7        0  ...    0    0          0      0      0      0        0      0   
9        0  ...    0    0          0      0      0      0        0      0   
10       0  ...    0    0          0      0      0      0        0      0   

    yum  yummy  
0     0      0  
1     0      0  
2     0      0  
3     0      0  
4     0      0  
5     0      0  
6     0      0  
7     0      0  
9     0      0  
10    0      0  

[10 rows x 915 columns]

In [137]:
# Paso 3: Implementación desde cero del clasificador Naïve Bayes
import numpy as np

class NaiveBayes:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.class_probs = {}
        self.word_probs = {}
        
        for c in self.classes:
            X_c = X[y == c]
            self.class_probs[c] = len(X_c) / len(X)
            total_wc = X_c.sum().sum()
            self.word_probs[c] = (X_c.sum() + 1) / (total_wc + X.shape[1])
            
    def predict(self, X):
        predictions = []
        for i in range(X.shape[0]):
            posteriors = {}
            row = X.iloc[i].values  # asegurar que sea un array
            for c in self.classes:
                log_prob = np.log(self.class_probs[c]) + np.sum(row * np.log(self.word_probs[c].values))
                posteriors[c] = log_prob
            predictions.append(max(posteriors, key=posteriors.get))
        return np.array(predictions)

In [139]:
# Paso 4: Entrenar y evaluar
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Separar datos
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y  # ✅ estratificar por clase
)

# Asegurar que sean DataFrames
X_train = pd.DataFrame(X_train, columns=X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)

# Entrenar modelo Naive Bayes
model = NaiveBayes()
model.fit(X_train, y_train)

# Predecir
y_pred = model.predict(X_test)

# Evaluación básica
accuracy = (y_pred == y_test.values).mean()
print(f'✅ Accuracy: {accuracy:.4f}')

# Evaluación completa
print("\n📊 Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

print("\n📈 Reporte de Clasificación:")
print(classification_report(y_test, y_pred))



✅ Accuracy: 0.3633

📊 Matriz de Confusión:
[[ 68 136  71]
 [ 84 213 102]
 [ 57 181  79]]

📈 Reporte de Clasificación:
              precision    recall  f1-score   support

    negative       0.33      0.25      0.28       275
     neutral       0.40      0.53      0.46       399
    positive       0.31      0.25      0.28       317

    accuracy                           0.36       991
   macro avg       0.35      0.34      0.34       991
weighted avg       0.35      0.36      0.35       991



In [143]:
import numpy as np
import pandas as pd

# Paso 1: Obtener clases
clases = np.unique(y_test)

# Paso 2: Inicializar matriz de confusión
conf_matrix = pd.DataFrame(0, index=clases, columns=clases)

# Paso 3: Llenar matriz de confusión
for true, pred in zip(y_test, y_pred):
    conf_matrix.loc[true, pred] += 1

print("📊 Matriz de Confusión:")
print(conf_matrix)

# Paso 4: Calcular precision, recall y F1 por clase
metricas = []

for clase in clases:
    TP = conf_matrix.loc[clase, clase]
    FP = conf_matrix[clase].sum() - TP
    FN = conf_matrix.loc[clase].sum() - TP
    
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    
    metricas.append({
        "Clase": clase,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1
    })

# Paso 5: Mostrar tabla de métricas
df_metricas = pd.DataFrame(metricas)
print("\n📈 Métricas por clase:")
print(df_metricas)

# Paso 6: Promedios macro
macro_avg = df_metricas[["Precision", "Recall", "F1-Score"]].mean()
print("\n📐 Promedio Macro:")
print(macro_avg)


📊 Matriz de Confusión:
          negative  neutral  positive
negative        68      136        71
neutral         84      213       102
positive        57      181        79

📈 Métricas por clase:
      Clase  Precision    Recall  F1-Score
0  negative   0.325359  0.247273  0.280992
1   neutral   0.401887  0.533835  0.458558
2  positive   0.313492  0.249211  0.277680

📐 Promedio Macro:
Precision    0.346913
Recall       0.343440
F1-Score     0.339076
dtype: float64


In [145]:
# Backend Flask para el modelo Naive Bayes entrenado
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    texto = data.get('text', '')
    if not texto:
        return jsonify({'error': 'No se proporcionó texto'}), 400

    vector = vectorizer.transform([texto])
    pred = model.predict(pd.DataFrame(vector.toarray(), columns=X.columns))
    return jsonify({'sentimiento': pred[0]})

if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/opt/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Fil

SystemExit: 1

/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [77]:
df["tweet"].value_counts()


tweet
neutral     1999
positive    1586
negative    1383
Name: count, dtype: int64